spring.application.name=consumer-api
server.port=8080

# Datasource
spring.datasource.url=jdbc:h2:mem:consumerdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.locale=pt_BR
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.deserialization.fail-on-unknown-properties=false
